import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case korean
    case english
    case japanese
    case simplifiedChinese
    case traditionalChinese
    case german
    case french
    case spanish
    case portugueseBrazil
    case italian
    case russian

    var id: String { rawValue }

    var bundleLanguageIdentifier: String {
        switch self {
        case .korean: return "ko"
        case .english: return "en"
        case .japanese: return "ja"
        case .simplifiedChinese: return "zh-Hans"
        case .traditionalChinese: return "zh-Hant"
        case .german: return "de"
        case .french: return "fr"
        case .spanish: return "es"
        case .portugueseBrazil: return "pt-BR"
        case .italian: return "it"
        case .russian: return "ru"
        }
    }

    var titleKey: String {
        switch self {
        case .korean: return "menu.language.korean"
        case .english: return "menu.language.english"
        case .japanese: return "menu.language.japanese"
        case .simplifiedChinese: return "menu.language.simplifiedChinese"
        case .traditionalChinese: return "menu.language.traditionalChinese"
        case .german: return "menu.language.german"
        case .french: return "menu.language.french"
        case .spanish: return "menu.language.spanish"
        case .portugueseBrazil: return "menu.language.portugueseBrazil"
        case .italian: return "menu.language.italian"
        case .russian: return "menu.language.russian"
        }
    }
}

final class LocalizationController: ObservableObject {
    nonisolated(unsafe) static let shared = LocalizationController()

    @Published private(set) var selectedLanguage: AppLanguage?

    private let defaultsKey = "appLanguageOverride"
    private let defaults: UserDefaults

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        let storedValue = defaults.string(forKey: defaultsKey)
        selectedLanguage = AppLanguage(rawValue: storedValue ?? "")
        if let selectedLanguage {
            synchronizeBundleLanguage(with: selectedLanguage)
        }
    }

    func setLanguage(_ language: AppLanguage) {
        guard selectedLanguage != language else {
            synchronizeBundleLanguage(with: language)
            return
        }
        selectedLanguage = language
        defaults.set(language.rawValue, forKey: defaultsKey)
        synchronizeBundleLanguage(with: language)
    }

    private func synchronizeBundleLanguage(with language: AppLanguage) {
        let preferredLanguages = [language.bundleLanguageIdentifier]
        guard defaults.stringArray(forKey: "AppleLanguages") != preferredLanguages else { return }
        defaults.set(preferredLanguages, forKey: "AppleLanguages")
    }
}

enum Localized {
    static var currentLanguage: AppLanguage {
        LocalizationController.shared.selectedLanguage
            ?? inferredLanguage(from: Locale.preferredLanguages.first)
    }

    static func inferredLanguage(from preferredLanguage: String?) -> AppLanguage {
        let preferred = preferredLanguage?.lowercased() ?? "en"
        if preferred.hasPrefix("ko") {
            return .korean
        }
        if preferred.hasPrefix("ja") {
            return .japanese
        }
        if preferred.contains("hant") {
            return .traditionalChinese
        }
        if preferred.hasPrefix("zh") {
            return .simplifiedChinese
        }
        if preferred.hasPrefix("de") {
            return .german
        }
        if preferred.hasPrefix("fr") {
            return .french
        }
        if preferred.hasPrefix("es") {
            return .spanish
        }
        if preferred.hasPrefix("pt") {
            return .portugueseBrazil
        }
        if preferred.hasPrefix("it") {
            return .italian
        }
        if preferred.hasPrefix("ru") {
            return .russian
        }
        return .english
    }

    static func string(_ key: String) -> String {
        activeTable[key] ?? english[key] ?? key
    }

    static func string(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: string(key), locale: Locale.current, arguments: arguments)
    }

    private static var activeTable: [String: String] {
        let language = currentLanguage

        switch language {
        case .korean: return korean
        case .english: return english
        case .japanese: return japanese
        case .simplifiedChinese: return simplifiedChinese
        case .traditionalChinese: return traditionalChinese
        case .german: return german
        case .french: return french
        case .spanish: return spanish
        case .portugueseBrazil: return portugueseBrazil
        case .italian: return italian
        case .russian: return russian
        }
    }

    private static let english: [String: String] = [
        "update.available": "Update",
        "menu.checkForUpdates": "Check for Updates…",
        "app.additionalCursors": "Additional Cursors",
        "app.additionalCursorHint": "Default: Use the macOS default cursor.\nUnless you have a specific reason, it's best to leave these as they are.",
        "app.noCursorLoaded": "No cursor loaded",
        "app.loadCursorFolderHint": "Load a cursor folder, then choose a role from the list to preview it.",
        "app.automaticMatchFailed": "Automatic matching failed",
        "app.automaticMatchFailedArrowFallback": "Automatic matching failed · using arrow fallback",
        "app.manualOverride": "Manual override",
        "app.automaticallyMatched": "Automatically matched",
        "app.automaticallyMatchedFromFolder": "Automatically matched from the folder",
        "app.changeCursorFile": "Change Cursor File",
        "app.arrowFallbackDescription": "A dedicated cursor for this role was not found, so the theme's arrow cursor is being used instead.",
        "app.automaticMatchKeywords": "Automatic Match Keywords",
        "app.inheritedMatchKeywords": "Suggested Match Keywords",
        "app.mousecape": "Mousecape Type",
        "app.currentSource": "Current Source",
        "app.automaticallyMatchedInsideSelectedFolder": "Automatically matched inside the selected folder",
        "app.cursorFolder": "Cursor Folder",
        "app.noFolderSelected": "No folder selected",
        "app.chooseFolder": "Choose Folder",
        "app.cursorWillAppearHere": "The cursor will appear here after you load one.",
        "systemApply.apply": "Apply to System Cursors",
        "systemApply.openPointerSettings": "Reset Default Cursor in macOS Settings",
        "systemApply.pointerSettingsHint": "In macOS Pointer settings, choose Reset Colors to return to the default cursor.",
        "systemApply.progressTitle": "Applying system cursors...",
        "systemApply.progressPreparing": "Preparing the selected cursor set.",
        "systemApply.progressRendering": "Reading cursor files and preparing images.",
        "systemApply.progressRegistering": "Registering cursors with macOS.",
        "systemApply.progressAgent": "Preparing automatic cursor apply at login.",
        "systemApply.progressDone": "Done.",
        "systemApply.successTitle": "Applied",
        "preview.large": "Preview",
        "preview.actualSize": "Actual Size",
        "export.sizeLabel": "Cursor Size",
        "alert.errorTitle": "Error",
        "alert.ok": "OK",
        "alert.dropCursorSelectionRequired": "Choose a cursor role before dropping a cursor file.",
        "alert.dropLoadFailed": "The dropped item could not be read. Try dropping the file or folder again.",
        "export.unknownAuthor": "Unknown Author",
        "role.arrow": "Normal / Pointer",
        "role.text": "Text",
        "role.link": "Link",
        "role.location": "Pin / Location",
        "role.precision": "Precision / Crosshair",
        "role.move": "Move",
        "role.unavailable": "Unavailable",
        "role.busy": "Busy",
        "role.working": "Background / Working",
        "role.help": "Help",
        "role.handwriting": "Handwriting",
        "role.person": "Person",
        "role.alternate": "Alternate",
        "role.verticalResize": "Vertical Resize",
        "role.horizontalResize": "Horizontal Resize",
        "role.diagonalResizeNWSE": "Diagonal Resize 1",
        "role.diagonalResizeNESW": "Diagonal Resize 2",
        "role.contextualMenu": "Contextual Menu",
        "role.dragCopy": "Drag Copy",
        "role.dragLink": "Drag Link",
        "role.disappearingItem": "Disappearing Item",
        "role.closeHand": "Closed Hand",
        "role.openHand": "Open Hand",
        "role.resizeUp": "Resize Up",
        "role.resizeDown": "Resize Down",
        "role.resizeLeft": "Resize Left",
        "role.resizeRight": "Resize Right",
        "role.verticalIBeam": "Vertical Text Selection",
        "role.zoomIn": "Zoom In",
        "role.zoomOut": "Zoom Out",
        "status.startingUp": "Starting up...",
        "status.chooseCursorFolder": "Choose a cursor folder.",
        "status.supportedFiles": "Supported files are .ani and .cur.",
        "status.systemApplySuccess": "Applied to system cursors. The login helper is enabled.",
        "status.systemApplyWarning": "Applied to system cursors, but the login helper was not confirmed: %@",
        "status.systemApplyFailure": "System cursor apply failed: %@",
        "status.loaded": "Loaded %@ · %d/%d roles mapped",
        "status.loadFailure": "Load failed: %@",
        "panel.chooseFolder": "Choose Folder",
        "panel.chooseCursor": "Choose Cursor",
        "menu.language": "Language",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "No theme folder is selected.",
        "error.themeFileMissing": "Theme file is missing: %@",
        "error.aniParsingFailed": "ANI parsing failed: %@",
        "error.unsupportedCursorPayload": "The cursor frame could not be read as an image.",
        "error.invalidThemeSelection.noCursorFiles": "This folder does not contain cursor files that can be used directly.\nChoose a folder that contains .ani or .cur files at the top level.",
        "error.unsupportedExtension": "Unsupported file extension: %@",
        "error.invalidRiffAconHeader": "The file does not have a RIFF ACON header.",
        "error.invalidChunkLength": "The chunk length is invalid.",
        "error.noFrames": "The file does not contain any frames.",
        "error.invalidIconChunkLength": "The icon chunk length is invalid.",
        "error.curTooShort": "The CUR data is too short.",
        "error.invalidCurHeader": "The file does not contain a valid CUR header.",
        "error.invalidCurEmbeddedRange": "The embedded CUR image range is invalid.",
        "error.noCursorsToExport": "There are no cursors to export.",
        "error.systemApplyExecutableMissing": "Cursie could not locate its executable for the login cursor helper.",
        "error.systemApplyBundleIdentifierMissing": "Cursie could not determine the app identifier needed by the login cursor helper.",
        "error.installCursieBeforeApplying": "Move Cursie to the Applications folder, then try again. An app running from a disk image cannot restore your cursor after login.",
        "error.cursorFileTooLarge": "The cursor file is too large. Files up to %d MB are supported.",
        "error.cursorTooManyFrames": "The cursor has too many frames. Up to %d frames are supported.",
        "error.cursorDimensionsTooLarge": "The cursor image is too large. Each side can be up to %d pixels.",
        "error.cursorRenderedDimensionsTooLarge": "The cursor image is too large at the selected scale. Each side can be up to %d pixels.",
        "error.cursorRenderedPayloadTooLarge": "The rendered animated cursor is too large. Reduce the cursor size or number of frames.",
        "error.mousecapeConflict": "Mousecape or mousecloak is currently running (%@). Quit it before applying Cursie cursors so the two apps do not fight over the system cursor."
    ]

    private static let korean: [String: String] = [
        "update.available": "업데이트",
        "menu.checkForUpdates": "업데이트 확인…",
        "app.additionalCursors": "추가 커서",
        "app.additionalCursorHint": "기본값: macOS 기본 커서 사용\n특별한 경우가 아니라면 그대로 두세요.",
        "app.noCursorLoaded": "불러온 커서가 없습니다",
        "app.loadCursorFolderHint": "커서 폴더를 불러온 뒤 왼쪽 목록에서 역할을 고르면 해당 커서를 표시합니다.",
        "app.automaticMatchFailed": "자동 매핑 실패",
        "app.automaticMatchFailedArrowFallback": "자동 매핑 실패 · 일반 커서 대체",
        "app.manualOverride": "수동 지정",
        "app.automaticallyMatched": "자동 매핑",
        "app.automaticallyMatchedFromFolder": "폴더에서 자동 매핑된 파일",
        "app.changeCursorFile": "커서 파일 변경",
        "app.arrowFallbackDescription": "이 역할에 맞는 커서를 찾지 못해 테마의 일반 커서로 대신 표시합니다.",
        "app.automaticMatchKeywords": "자동 매핑 키워드",
        "app.inheritedMatchKeywords": "추천 키워드",
        "app.mousecape": "Mousecape 유형",
        "app.currentSource": "현재 소스",
        "app.automaticallyMatchedInsideSelectedFolder": "선택한 폴더 안에서 자동 매핑",
        "app.cursorFolder": "커서 폴더",
        "app.noFolderSelected": "선택된 폴더 없음",
        "app.chooseFolder": "폴더 선택",
        "app.cursorWillAppearHere": "커서를 불러오면 여기에 표시됩니다.",
        "systemApply.apply": "시스템 커서에 적용",
        "systemApply.openPointerSettings": "macOS 설정에서 기본 커서로 재설정",
        "systemApply.pointerSettingsHint": "macOS 포인터 설정에서 ‘색상 재설정’을 눌러 기본 커서로 되돌릴 수 있습니다.",
        "systemApply.progressTitle": "시스템 커서 적용 중...",
        "systemApply.progressPreparing": "선택한 커서 세트를 준비하고 있습니다.",
        "systemApply.progressRendering": "커서 파일을 읽고 이미지를 준비하고 있습니다.",
        "systemApply.progressRegistering": "macOS에 시스템 커서를 등록하고 있습니다.",
        "systemApply.progressAgent": "로그인 시 커서를 자동으로 적용하도록 준비하고 있습니다.",
        "systemApply.progressDone": "완료했습니다.",
        "systemApply.successTitle": "적용 완료",
        "preview.large": "크게 보기",
        "preview.actualSize": "실제 크기",
        "export.sizeLabel": "커서 크기",
        "alert.errorTitle": "오류",
        "alert.ok": "확인",
        "alert.dropCursorSelectionRequired": "커서 파일을 끌어넣기 전에 왼쪽에서 커서 역할을 먼저 선택하세요.",
        "alert.dropLoadFailed": "끌어놓은 항목을 읽지 못했습니다. 파일이나 폴더를 다시 끌어넣어 보세요.",
        "export.unknownAuthor": "알 수 없음",
        "role.arrow": "일반 / 포인터",
        "role.text": "텍스트",
        "role.link": "링크",
        "role.location": "위치 선택",
        "role.precision": "정밀도 / 십자선",
        "role.move": "이동",
        "role.unavailable": "사용 불가",
        "role.busy": "사용 중",
        "role.working": "백그라운드 / 작업 중",
        "role.help": "도움말",
        "role.handwriting": "손글씨",
        "role.person": "사람",
        "role.alternate": "대체",
        "role.verticalResize": "수직 크기 조절",
        "role.horizontalResize": "수평 크기 조절",
        "role.diagonalResizeNWSE": "대각선 크기 조절 1",
        "role.diagonalResizeNESW": "대각선 크기 조절 2",
        "role.contextualMenu": "컨텍스트 메뉴",
        "role.dragCopy": "드래그 복사",
        "role.dragLink": "드래그 링크",
        "role.disappearingItem": "사라지는 항목",
        "role.closeHand": "닫힌 손",
        "role.openHand": "열린 손",
        "role.resizeUp": "위로 크기 조절",
        "role.resizeDown": "아래로 크기 조절",
        "role.resizeLeft": "왼쪽으로 크기 조절",
        "role.resizeRight": "오른쪽으로 크기 조절",
        "role.verticalIBeam": "세로 텍스트 선택",
        "role.zoomIn": "확대",
        "role.zoomOut": "축소",
        "status.startingUp": "초기화 중...",
        "status.chooseCursorFolder": "커서 폴더를 선택하세요.",
        "status.supportedFiles": "지원하는 파일은 .ani 또는 .cur 입니다.",
        "status.systemApplySuccess": "시스템 커서에 적용했습니다. 로그인 복구 헬퍼가 켜졌습니다.",
        "status.systemApplyWarning": "시스템 커서에 적용했습니다. 다만 로그인 복구 헬퍼 준비 확인은 실패했습니다: %@",
        "status.systemApplyFailure": "시스템 커서 적용 실패: %@",
        "status.loaded": "%@ 불러옴 · %d/%d개 역할 지정됨",
        "status.loadFailure": "불러오기 실패: %@",
        "panel.chooseFolder": "폴더 선택",
        "panel.chooseCursor": "커서 선택",
        "menu.language": "언어",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "테마 폴더가 선택되지 않았습니다.",
        "error.themeFileMissing": "테마 파일이 없습니다: %@",
        "error.aniParsingFailed": "ANI 파싱 실패: %@",
        "error.unsupportedCursorPayload": "커서 프레임을 이미지로 읽지 못했습니다.",
        "error.invalidThemeSelection.noCursorFiles": "이 폴더에는 바로 적용할 커서 파일이 없습니다.\n.ani 또는 .cur 파일이 직접 들어 있는 폴더를 선택하세요.",
        "error.unsupportedExtension": "지원하지 않는 확장자입니다: %@",
        "error.invalidRiffAconHeader": "RIFF ACON 헤더가 아닙니다.",
        "error.invalidChunkLength": "청크 길이가 잘못되었습니다.",
        "error.noFrames": "프레임이 없습니다.",
        "error.invalidIconChunkLength": "icon 청크 길이가 잘못되었습니다.",
        "error.curTooShort": "CUR 데이터가 너무 짧습니다.",
        "error.invalidCurHeader": "CUR 헤더가 아닙니다.",
        "error.invalidCurEmbeddedRange": "CUR 내부 이미지 범위가 잘못되었습니다.",
        "error.noCursorsToExport": "내보낼 커서가 없습니다.",
        "error.systemApplyExecutableMissing": "로그인 커서 복구 헬퍼에 사용할 Cursie 실행 파일을 찾지 못했습니다.",
        "error.systemApplyBundleIdentifierMissing": "로그인 커서 복구에 필요한 Cursie 앱 식별자를 찾지 못했습니다.",
        "error.installCursieBeforeApplying": "Cursie를 응용 프로그램 폴더로 옮긴 뒤 다시 적용하세요. 디스크 이미지에서 실행 중인 앱은 로그인 후 커서를 다시 적용할 수 없습니다.",
        "error.cursorFileTooLarge": "커서 파일이 너무 큽니다. 최대 %dMB까지 지원합니다.",
        "error.cursorTooManyFrames": "커서 프레임이 너무 많습니다. 최대 %d개까지 지원합니다.",
        "error.cursorDimensionsTooLarge": "커서 이미지가 너무 큽니다. 한 변은 최대 %d픽셀까지 지원합니다.",
        "error.cursorRenderedDimensionsTooLarge": "선택한 배율로 만든 커서 이미지가 너무 큽니다. 한 변은 최대 %d픽셀입니다.",
        "error.cursorRenderedPayloadTooLarge": "애니메이션 커서를 처리한 이미지가 너무 큽니다. 커서 크기나 프레임 수를 줄여 주세요.",
        "error.mousecapeConflict": "Mousecape 또는 mousecloak이 실행 중입니다(%@). 두 앱이 시스템 커서를 서로 다시 적용하지 않도록 종료한 뒤 Cursie 커서를 적용하세요."
    ]

    private static let japanese: [String: String] = [
        "update.available": "アップデート",
        "menu.checkForUpdates": "アップデートを確認…",
        "app.additionalCursors": "追加カーソル",
        "app.additionalCursorHint": "デフォルト：macOSの標準カーソルを使用\n特に変更する必要がなければ、そのままお使いください。",
        "app.noCursorLoaded": "カーソルが読み込まれていません",
        "app.loadCursorFolderHint": "カーソルフォルダを読み込んだあと、左の一覧から役割を選ぶとプレビューできます。",
        "app.automaticMatchFailed": "自動割り当てに失敗しました",
        "app.automaticMatchFailedArrowFallback": "自動割り当てに失敗 · 標準カーソルを使用",
        "app.manualOverride": "手動指定",
        "app.automaticallyMatched": "自動割り当て",
        "app.automaticallyMatchedFromFolder": "フォルダから自動で割り当てたファイル",
        "app.changeCursorFile": "カーソルファイルを変更",
        "app.arrowFallbackDescription": "この役割専用のカーソルが見つからなかったため、このテーマの通常カーソルで代用しています。",
        "app.automaticMatchKeywords": "自動割り当てのキーワード",
        "app.inheritedMatchKeywords": "候補キーワード",
        "app.mousecape": "Mousecapeの種類",
        "app.currentSource": "現在のソース",
        "app.automaticallyMatchedInsideSelectedFolder": "選択したフォルダ内で自動割り当て",
        "app.cursorFolder": "カーソルフォルダ",
        "app.noFolderSelected": "フォルダが選択されていません",
        "app.chooseFolder": "フォルダを選択",
        "app.cursorWillAppearHere": "カーソルを読み込むとここに表示されます。",
        "systemApply.apply": "システムカーソルに適用",
        "systemApply.openPointerSettings": "macOSの設定で標準カーソルに戻す",
        "systemApply.pointerSettingsHint": "macOSのポインタ設定で「カラーをリセット」を選ぶと、デフォルトカーソルに戻せます。",
        "systemApply.progressTitle": "システムカーソルを適用中...",
        "systemApply.progressPreparing": "選択したカーソルセットを準備しています。",
        "systemApply.progressRendering": "カーソルファイルを読み込み、画像を準備しています。",
        "systemApply.progressRegistering": "macOS にシステムカーソルを登録しています。",
        "systemApply.progressAgent": "ログイン時にカーソルを自動適用する準備をしています。",
        "systemApply.progressDone": "完了しました。",
        "systemApply.successTitle": "適用完了",
        "preview.large": "拡大表示",
        "preview.actualSize": "実際のサイズ",
        "export.sizeLabel": "カーソルサイズ",
        "alert.errorTitle": "エラー",
        "alert.ok": "OK",
        "alert.dropCursorSelectionRequired": "カーソルファイルをドロップする前に、左側でカーソルの役割を選択してください。",
        "alert.dropLoadFailed": "ドロップされた項目を読み取れませんでした。ファイルまたはフォルダをもう一度ドロップしてください。",
        "export.unknownAuthor": "不明",
        "role.arrow": "標準 / ポインタ",
        "role.text": "テキスト",
        "role.link": "リンク",
        "role.location": "位置選択",
        "role.precision": "精密 / 十字線",
        "role.move": "移動",
        "role.unavailable": "使用不可",
        "role.busy": "使用中",
        "role.working": "バックグラウンド / 作業中",
        "role.help": "ヘルプ",
        "role.handwriting": "手書き",
        "role.person": "人",
        "role.alternate": "代替",
        "role.verticalResize": "垂直サイズ変更",
        "role.horizontalResize": "水平サイズ変更",
        "role.diagonalResizeNWSE": "斜めサイズ変更 1",
        "role.diagonalResizeNESW": "斜めサイズ変更 2",
        "role.contextualMenu": "コンテキストメニュー",
        "role.dragCopy": "コピー",
        "role.dragLink": "リンクを作成",
        "role.disappearingItem": "消える項目",
        "role.closeHand": "閉じた手のひら",
        "role.openHand": "開いた手のひら",
        "role.resizeUp": "上方向にサイズ変更",
        "role.resizeDown": "下方向にサイズ変更",
        "role.resizeLeft": "左方向にサイズ変更",
        "role.resizeRight": "右方向にサイズ変更",
        "role.verticalIBeam": "縦書きテキスト選択",
        "role.zoomIn": "拡大",
        "role.zoomOut": "縮小",
        "status.startingUp": "初期化中...",
        "status.chooseCursorFolder": "カーソルフォルダを選択してください。",
        "status.supportedFiles": "対応ファイルは .ani と .cur です。",
        "status.systemApplySuccess": "システムカーソルに適用しました。ログインヘルパーが有効です。",
        "status.systemApplyWarning": "システムカーソルに適用しましたが、ログインヘルパーを確認できませんでした: %@",
        "status.systemApplyFailure": "システムカーソルの適用に失敗しました: %@",
        "status.loaded": "%@ を読み込みました · %d/%d種類を割り当て済み",
        "status.loadFailure": "読み込み失敗: %@",
        "panel.chooseFolder": "フォルダを選択",
        "panel.chooseCursor": "カーソルを選択",
        "menu.language": "言語",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "テーマフォルダが選択されていません。",
        "error.themeFileMissing": "テーマファイルが見つかりません: %@",
        "error.aniParsingFailed": "ANI の解析に失敗しました: %@",
        "error.unsupportedCursorPayload": "カーソルフレームを画像として読み取れませんでした。",
        "error.invalidThemeSelection.noCursorFiles": "このフォルダには直接使えるカーソルファイルがありません。\n最上位に .ani または .cur ファイルがあるフォルダを選択してください。",
        "error.unsupportedExtension": "未対応の拡張子です: %@",
        "error.invalidRiffAconHeader": "RIFF ACON ヘッダーではありません。",
        "error.invalidChunkLength": "チャンク長が正しくありません。",
        "error.noFrames": "フレームがありません。",
        "error.invalidIconChunkLength": "icon チャンク長が正しくありません。",
        "error.curTooShort": "CUR データが短すぎます。",
        "error.invalidCurHeader": "有効な CUR ヘッダーではありません。",
        "error.invalidCurEmbeddedRange": "CUR 内部画像の範囲が正しくありません。",
        "error.noCursorsToExport": "書き出すカーソルがありません。",
        "error.systemApplyExecutableMissing": "ログイン用カーソルヘルパーに使用する Cursie 実行ファイルが見つかりません。",
        "error.systemApplyBundleIdentifierMissing": "ログインヘルパーに必要なCursieのアプリ識別子を取得できませんでした。",
        "error.installCursieBeforeApplying": "Cursieをアプリケーションフォルダに移してから、もう一度お試しください。ディスクイメージから実行中のアプリは、ログイン後にカーソルを復元できません。",
        "error.cursorFileTooLarge": "カーソルファイルが大きすぎます。最大%d MBまで対応しています。",
        "error.cursorTooManyFrames": "カーソルのフレーム数が多すぎます。最大%dフレームまで対応しています。",
        "error.cursorDimensionsTooLarge": "カーソル画像が大きすぎます。各辺は最大%dピクセルです。",
        "error.cursorRenderedDimensionsTooLarge": "選択した倍率ではカーソル画像が大きすぎます。各辺は最大%dピクセルです。",
        "error.cursorRenderedPayloadTooLarge": "処理後のアニメーションカーソルが大きすぎます。カーソルサイズまたはフレーム数を減らしてください。",
        "error.mousecapeConflict": "Mousecape または mousecloak が実行中です（%@）。2つのアプリがシステムカーソルを競合して再適用しないよう、終了してから Cursie カーソルを適用してください。"
    ]

    private static let simplifiedChinese: [String: String] = [
        "update.available": "更新",
        "menu.checkForUpdates": "检查更新…",
        "app.additionalCursors": "其他光标",
        "app.additionalCursorHint": "默认值：使用 macOS 默认光标\n除非有特殊情况，否则建议保持原样。",
        "app.noCursorLoaded": "没有已加载的光标",
        "app.loadCursorFolderHint": "加载光标文件夹后，可在左侧列表中选择角色进行预览。",
        "app.automaticMatchFailed": "自动匹配失败",
        "app.automaticMatchFailedArrowFallback": "自动匹配失败 · 使用普通光标替代",
        "app.manualOverride": "手动指定",
        "app.automaticallyMatched": "自动匹配",
        "app.automaticallyMatchedFromFolder": "从文件夹自动匹配的文件",
        "app.changeCursorFile": "更改光标文件",
        "app.arrowFallbackDescription": "未找到此角色专用的光标，因此改用该主题的普通光标。",
        "app.automaticMatchKeywords": "自动匹配关键词",
        "app.inheritedMatchKeywords": "推荐关键词",
        "app.mousecape": "Mousecape 类型",
        "app.currentSource": "当前来源",
        "app.automaticallyMatchedInsideSelectedFolder": "在所选文件夹内自动匹配",
        "app.cursorFolder": "光标文件夹",
        "app.noFolderSelected": "未选择文件夹",
        "app.chooseFolder": "选择文件夹",
        "app.cursorWillAppearHere": "加载光标后会显示在这里。",
        "systemApply.apply": "应用到系统光标",
        "systemApply.openPointerSettings": "在 macOS 设置中重置默认光标",
        "systemApply.pointerSettingsHint": "在 macOS 指针设置中选择“重置颜色”，即可恢复默认光标。",
        "systemApply.progressTitle": "正在应用系统光标...",
        "systemApply.progressPreparing": "正在准备所选光标集。",
        "systemApply.progressRendering": "正在读取光标文件并准备图像。",
        "systemApply.progressRegistering": "正在向 macOS 注册系统光标。",
        "systemApply.progressAgent": "正在准备登录时自动应用光标。",
        "systemApply.progressDone": "完成。",
        "systemApply.successTitle": "已应用",
        "preview.large": "放大预览",
        "preview.actualSize": "实际大小",
        "export.sizeLabel": "光标大小",
        "alert.errorTitle": "错误",
        "alert.ok": "确定",
        "alert.dropCursorSelectionRequired": "拖放光标文件前，请先在左侧选择光标角色。",
        "alert.dropLoadFailed": "无法读取拖放的项目。请重新拖放文件或文件夹。",
        "export.unknownAuthor": "未知",
        "role.arrow": "普通 / 指针",
        "role.text": "文本",
        "role.link": "链接",
        "role.location": "位置选择",
        "role.precision": "精确 / 十字线",
        "role.move": "移动",
        "role.unavailable": "不可用",
        "role.busy": "忙碌",
        "role.working": "后台 / 工作中",
        "role.help": "帮助",
        "role.handwriting": "手写",
        "role.person": "人物",
        "role.alternate": "替代",
        "role.verticalResize": "垂直调整大小",
        "role.horizontalResize": "水平调整大小",
        "role.diagonalResizeNWSE": "对角线调整大小 1",
        "role.diagonalResizeNESW": "对角线调整大小 2",
        "role.contextualMenu": "上下文菜单",
        "role.dragCopy": "拖动复制",
        "role.dragLink": "拖动创建链接",
        "role.disappearingItem": "消失项目",
        "role.closeHand": "握紧的手",
        "role.openHand": "张开的手",
        "role.resizeUp": "向上调整大小",
        "role.resizeDown": "向下调整大小",
        "role.resizeLeft": "向左调整大小",
        "role.resizeRight": "向右调整大小",
        "role.verticalIBeam": "纵向文本选择",
        "role.zoomIn": "放大",
        "role.zoomOut": "缩小",
        "status.startingUp": "正在初始化...",
        "status.chooseCursorFolder": "请选择光标文件夹。",
        "status.supportedFiles": "支持的文件格式为 .ani 和 .cur。",
        "status.systemApplySuccess": "已应用到系统光标。登录辅助程序已启用。",
        "status.systemApplyWarning": "已应用到系统光标，但无法确认登录辅助程序：%@",
        "status.systemApplyFailure": "系统光标应用失败：%@",
        "status.loaded": "已加载 %@ · 已映射 %d/%d 个角色",
        "status.loadFailure": "加载失败：%@",
        "panel.chooseFolder": "选择文件夹",
        "panel.chooseCursor": "选择光标",
        "menu.language": "语言",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "未选择主题文件夹。",
        "error.themeFileMissing": "缺少主题文件：%@",
        "error.aniParsingFailed": "ANI 解析失败：%@",
        "error.unsupportedCursorPayload": "无法将光标帧读取为图像。",
        "error.invalidThemeSelection.noCursorFiles": "此文件夹中没有可直接使用的光标文件。\n请选择顶层包含 .ani 或 .cur 文件的文件夹。",
        "error.unsupportedExtension": "不支持的扩展名：%@",
        "error.invalidRiffAconHeader": "不是有效的 RIFF ACON 头。",
        "error.invalidChunkLength": "块长度无效。",
        "error.noFrames": "没有帧。",
        "error.invalidIconChunkLength": "icon 块长度无效。",
        "error.curTooShort": "CUR 数据过短。",
        "error.invalidCurHeader": "不是有效的 CUR 头。",
        "error.invalidCurEmbeddedRange": "CUR 内嵌图像范围无效。",
        "error.noCursorsToExport": "没有可导出的光标。",
        "error.systemApplyExecutableMissing": "Cursie 找不到用于登录光标辅助程序的可执行文件。",
        "error.systemApplyBundleIdentifierMissing": "Cursie 无法获取登录辅助程序所需的应用标识符。",
        "error.installCursieBeforeApplying": "请先将 Cursie 移到“应用程序”文件夹，然后重试。从磁盘映像运行的应用无法在登录后恢复光标。",
        "error.cursorFileTooLarge": "光标文件过大。最大支持 %d MB。",
        "error.cursorTooManyFrames": "光标帧数过多。最多支持 %d 帧。",
        "error.cursorDimensionsTooLarge": "光标图像过大。每边最多支持 %d 像素。",
        "error.cursorRenderedDimensionsTooLarge": "按所选缩放比例生成的光标图像过大。每边最多支持 %d 像素。",
        "error.cursorRenderedPayloadTooLarge": "处理后的动画光标过大。请减小光标尺寸或帧数。",
        "error.mousecapeConflict": "Mousecape 或 mousecloak 当前正在运行（%@）。请先退出它，以免两个应用争夺系统光标。"
    ]

    private static let traditionalChinese: [String: String] = [
        "update.available": "更新",
        "menu.checkForUpdates": "檢查更新…",
        "app.additionalCursors": "其他游標",
        "app.additionalCursorHint": "預設值：使用 macOS 預設游標\n除非有特殊情況，否則建議維持原樣。",
        "app.noCursorLoaded": "沒有已載入的游標",
        "app.loadCursorFolderHint": "載入游標資料夾後，可在左側列表中選擇角色進行預覽。",
        "app.automaticMatchFailed": "自動配對失敗",
        "app.automaticMatchFailedArrowFallback": "自動配對失敗 · 使用一般游標替代",
        "app.manualOverride": "手動指定",
        "app.automaticallyMatched": "自動配對",
        "app.automaticallyMatchedFromFolder": "從資料夾自動配對的檔案",
        "app.changeCursorFile": "變更游標檔案",
        "app.arrowFallbackDescription": "找不到此角色專用的游標，因此改用此主題的一般游標。",
        "app.automaticMatchKeywords": "自動配對關鍵字",
        "app.inheritedMatchKeywords": "建議關鍵字",
        "app.mousecape": "Mousecape 類型",
        "app.currentSource": "目前來源",
        "app.automaticallyMatchedInsideSelectedFolder": "在所選資料夾中自動配對",
        "app.cursorFolder": "游標資料夾",
        "app.noFolderSelected": "未選擇資料夾",
        "app.chooseFolder": "選擇資料夾",
        "app.cursorWillAppearHere": "載入游標後會顯示在這裡。",
        "systemApply.apply": "套用到系統游標",
        "systemApply.openPointerSettings": "在 macOS 設定中重設預設游標",
        "systemApply.pointerSettingsHint": "在 macOS 指標設定中選擇「重設顏色」，即可還原預設游標。",
        "systemApply.progressTitle": "正在套用系統游標...",
        "systemApply.progressPreparing": "正在準備所選游標組。",
        "systemApply.progressRendering": "正在讀取游標檔案並準備影像。",
        "systemApply.progressRegistering": "正在向 macOS 註冊系統游標。",
        "systemApply.progressAgent": "正在準備登入時自動套用游標。",
        "systemApply.progressDone": "完成。",
        "systemApply.successTitle": "已套用",
        "preview.large": "放大預覽",
        "preview.actualSize": "實際大小",
        "export.sizeLabel": "游標大小",
        "alert.errorTitle": "錯誤",
        "alert.ok": "確定",
        "alert.dropCursorSelectionRequired": "拖放游標檔案前，請先在左側選擇游標角色。",
        "alert.dropLoadFailed": "無法讀取拖放的項目。請重新拖放檔案或資料夾。",
        "export.unknownAuthor": "未知",
        "role.arrow": "普通 / 指標",
        "role.text": "文字",
        "role.link": "連結",
        "role.location": "位置選擇",
        "role.precision": "精確 / 十字線",
        "role.move": "移動",
        "role.unavailable": "不可用",
        "role.busy": "忙碌",
        "role.working": "背景 / 工作中",
        "role.help": "說明",
        "role.handwriting": "手寫",
        "role.person": "人物",
        "role.alternate": "替代",
        "role.verticalResize": "垂直調整大小",
        "role.horizontalResize": "水平調整大小",
        "role.diagonalResizeNWSE": "對角線調整大小 1",
        "role.diagonalResizeNESW": "對角線調整大小 2",
        "role.contextualMenu": "情境選單",
        "role.dragCopy": "拖移以拷貝",
        "role.dragLink": "拖移以建立連結",
        "role.disappearingItem": "消失項目",
        "role.closeHand": "握緊的手",
        "role.openHand": "張開的手",
        "role.resizeUp": "向上調整大小",
        "role.resizeDown": "向下調整大小",
        "role.resizeLeft": "向左調整大小",
        "role.resizeRight": "向右調整大小",
        "role.verticalIBeam": "垂直文字選取",
        "role.zoomIn": "放大",
        "role.zoomOut": "縮小",
        "status.startingUp": "初始化中...",
        "status.chooseCursorFolder": "請選擇游標資料夾。",
        "status.supportedFiles": "支援的檔案格式為 .ani 與 .cur。",
        "status.systemApplySuccess": "已套用到系統游標。登入輔助程式已啟用。",
        "status.systemApplyWarning": "已套用到系統游標，但無法確認登入輔助程式：%@",
        "status.systemApplyFailure": "系統游標套用失敗：%@",
        "status.loaded": "已載入 %@ · 已對應 %d/%d 個角色",
        "status.loadFailure": "載入失敗：%@",
        "panel.chooseFolder": "選擇資料夾",
        "panel.chooseCursor": "選擇游標",
        "menu.language": "語言",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "未選擇主題資料夾。",
        "error.themeFileMissing": "缺少主題檔案：%@",
        "error.aniParsingFailed": "ANI 解析失敗：%@",
        "error.unsupportedCursorPayload": "無法將游標影格讀取為影像。",
        "error.invalidThemeSelection.noCursorFiles": "此資料夾中沒有可直接使用的游標檔案。\n請選擇頂層包含 .ani 或 .cur 檔案的資料夾。",
        "error.unsupportedExtension": "不支援的副檔名：%@",
        "error.invalidRiffAconHeader": "不是有效的 RIFF ACON 標頭。",
        "error.invalidChunkLength": "區塊長度無效。",
        "error.noFrames": "沒有影格。",
        "error.invalidIconChunkLength": "icon 區塊長度無效。",
        "error.curTooShort": "CUR 資料過短。",
        "error.invalidCurHeader": "不是有效的 CUR 標頭。",
        "error.invalidCurEmbeddedRange": "CUR 內嵌影像範圍無效。",
        "error.noCursorsToExport": "沒有可匯出的游標。",
        "error.systemApplyExecutableMissing": "Cursie 找不到登入游標輔助程式所需的執行檔。",
        "error.systemApplyBundleIdentifierMissing": "Cursie 無法取得登入輔助程式所需的 App 識別碼。",
        "error.installCursieBeforeApplying": "請先將 Cursie 移到「應用程式」資料夾，然後再試一次。從磁碟映像執行的 App 無法在登入後還原游標。",
        "error.cursorFileTooLarge": "游標檔案過大。最大支援 %d MB。",
        "error.cursorTooManyFrames": "游標影格過多。最多支援 %d 個影格。",
        "error.cursorDimensionsTooLarge": "游標影像過大。每邊最多支援 %d 像素。",
        "error.cursorRenderedDimensionsTooLarge": "依所選縮放比例產生的游標影像過大。每邊最多支援 %d 像素。",
        "error.cursorRenderedPayloadTooLarge": "處理後的動畫游標過大。請縮小游標尺寸或減少影格數。",
        "error.mousecapeConflict": "Mousecape 或 mousecloak 目前正在執行（%@）。請先結束它，以免兩個應用程式互相重套系統游標。"
    ]

    private static let german: [String: String] = [
        "update.available": "Update",
        "menu.checkForUpdates": "Nach Updates suchen…",
        "app.additionalCursors": "Zusätzliche Cursor",
        "app.additionalCursorHint": "Standard: den macOS-Standardcursor verwenden.\nLassen Sie diese am besten unverändert, außer in besonderen Fällen.",
        "app.noCursorLoaded": "Kein Cursor geladen",
        "app.loadCursorFolderHint": "Laden Sie einen Cursor-Ordner und wählen Sie dann links eine Rolle zur Vorschau aus.",
        "app.automaticMatchFailed": "Automatische Zuordnung fehlgeschlagen",
        "app.automaticMatchFailedArrowFallback": "Automatische Zuordnung fehlgeschlagen · Standardcursor als Ersatz",
        "app.manualOverride": "Manuelle Zuweisung",
        "app.automaticallyMatched": "Automatisch zugeordnet",
        "app.automaticallyMatchedFromFolder": "Automatisch aus dem Ordner zugeordnet",
        "app.changeCursorFile": "Cursor-Datei ändern",
        "app.arrowFallbackDescription": "Für diese Rolle wurde kein eigener Cursor gefunden, daher wird stattdessen der Standardcursor des Themes verwendet.",
        "app.automaticMatchKeywords": "Schlüsselwörter für automatische Zuordnung",
        "app.inheritedMatchKeywords": "Empfohlene Schlüsselwörter",
        "app.mousecape": "Mousecape-Typ",
        "app.currentSource": "Aktuelle Quelle",
        "app.automaticallyMatchedInsideSelectedFolder": "Im ausgewählten Ordner automatisch zugeordnet",
        "app.cursorFolder": "Cursor-Ordner",
        "app.noFolderSelected": "Kein Ordner ausgewählt",
        "app.chooseFolder": "Ordner wählen",
        "app.cursorWillAppearHere": "Der Cursor wird hier angezeigt, sobald Sie einen laden.",
        "systemApply.apply": "Auf Systemcursor anwenden",
        "systemApply.openPointerSettings": "Standardcursor in den macOS-Einstellungen zurücksetzen",
        "systemApply.pointerSettingsHint": "Wählen Sie in den macOS-Zeigereinstellungen „Farben zurücksetzen“, um zum Standardcursor zurückzukehren.",
        "systemApply.progressTitle": "Systemcursor werden angewendet...",
        "systemApply.progressPreparing": "Ausgewählten Cursorsatz vorbereiten.",
        "systemApply.progressRendering": "Cursor-Dateien lesen und Bilder vorbereiten.",
        "systemApply.progressRegistering": "Cursor bei macOS registrieren.",
        "systemApply.progressAgent": "Automatische Cursor-Anwendung beim Anmelden vorbereiten.",
        "systemApply.progressDone": "Fertig.",
        "systemApply.successTitle": "Angewendet",
        "preview.large": "Große Vorschau",
        "preview.actualSize": "Tatsächliche Größe",
        "export.sizeLabel": "Cursorgröße",
        "alert.errorTitle": "Fehler",
        "alert.ok": "OK",
        "alert.dropCursorSelectionRequired": "Wählen Sie links eine Cursor-Rolle aus, bevor Sie eine Cursor-Datei ablegen.",
        "alert.dropLoadFailed": "Das abgelegte Element konnte nicht gelesen werden. Legen Sie die Datei oder den Ordner erneut ab.",
        "export.unknownAuthor": "Unbekannt",
        "role.arrow": "Normal / Zeiger",
        "role.text": "Text",
        "role.link": "Link",
        "role.location": "Standortauswahl",
        "role.precision": "Präzision / Fadenkreuz",
        "role.move": "Bewegen",
        "role.unavailable": "Nicht verfügbar",
        "role.busy": "Beschäftigt",
        "role.working": "Hintergrund / In Arbeit",
        "role.help": "Hilfe",
        "role.handwriting": "Handschrift",
        "role.person": "Person",
        "role.alternate": "Alternativ",
        "role.verticalResize": "Vertikale Größenänderung",
        "role.horizontalResize": "Horizontale Größenänderung",
        "role.diagonalResizeNWSE": "Diagonale Größenänderung 1",
        "role.diagonalResizeNESW": "Diagonale Größenänderung 2",
        "role.contextualMenu": "Kontextmenü",
        "role.dragCopy": "Ziehen zum Kopieren",
        "role.dragLink": "Ziehen zum Verknüpfen",
        "role.disappearingItem": "Verschwindendes Element",
        "role.closeHand": "Geschlossene Hand",
        "role.openHand": "Offene Hand",
        "role.resizeUp": "Nach oben vergrößern",
        "role.resizeDown": "Nach unten vergrößern",
        "role.resizeLeft": "Nach links vergrößern",
        "role.resizeRight": "Nach rechts vergrößern",
        "role.verticalIBeam": "Vertikale Textauswahl",
        "role.zoomIn": "Vergrößern",
        "role.zoomOut": "Verkleinern",
        "status.startingUp": "Initialisierung...",
        "status.chooseCursorFolder": "Wählen Sie einen Cursor-Ordner.",
        "status.supportedFiles": "Unterstützte Dateien sind .ani und .cur.",
        "status.systemApplySuccess": "Auf Systemcursor angewendet. Der Anmeldehelfer ist aktiviert.",
        "status.systemApplyWarning": "Auf Systemcursor angewendet, aber der Anmeldehelfer konnte nicht bestätigt werden: %@",
        "status.systemApplyFailure": "Anwenden der Systemcursor fehlgeschlagen: %@",
        "status.loaded": "%@ geladen · %d/%d Rollen zugeordnet",
        "status.loadFailure": "Laden fehlgeschlagen: %@",
        "panel.chooseFolder": "Ordner wählen",
        "panel.chooseCursor": "Cursor wählen",
        "menu.language": "Sprache",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Kein Theme-Ordner ausgewählt.",
        "error.themeFileMissing": "Theme-Datei fehlt: %@",
        "error.aniParsingFailed": "ANI-Analyse fehlgeschlagen: %@",
        "error.unsupportedCursorPayload": "Der Cursor-Frame konnte nicht als Bild gelesen werden.",
        "error.invalidThemeSelection.noCursorFiles": "Dieser Ordner enthält keine direkt nutzbaren Cursor-Dateien.\nWählen Sie einen Ordner, der .ani- oder .cur-Dateien auf oberster Ebene enthält.",
        "error.unsupportedExtension": "Nicht unterstützte Dateiendung: %@",
        "error.invalidRiffAconHeader": "Die Datei hat keinen gültigen RIFF-ACON-Header.",
        "error.invalidChunkLength": "Die Chunk-Länge ist ungültig.",
        "error.noFrames": "Die Datei enthält keine Frames.",
        "error.invalidIconChunkLength": "Die Länge des icon-Chunks ist ungültig.",
        "error.curTooShort": "Die CUR-Daten sind zu kurz.",
        "error.invalidCurHeader": "Die Datei enthält keinen gültigen CUR-Header.",
        "error.invalidCurEmbeddedRange": "Der eingebettete CUR-Bereich ist ungültig.",
        "error.noCursorsToExport": "Es gibt keine Cursor zum Exportieren.",
        "error.systemApplyExecutableMissing": "Cursie konnte die ausführbare Datei für den Anmelde-Cursorhelfer nicht finden.",
        "error.systemApplyBundleIdentifierMissing": "Cursie konnte die für den Anmeldehelfer benötigte App-ID nicht ermitteln.",
        "error.installCursieBeforeApplying": "Verschieben Sie Cursie in den Programme-Ordner und versuchen Sie es erneut. Eine App, die von einem Disk-Image ausgeführt wird, kann den Cursor nach der Anmeldung nicht wiederherstellen.",
        "error.cursorFileTooLarge": "Die Cursordatei ist zu groß. Unterstützt werden bis zu %d MB.",
        "error.cursorTooManyFrames": "Der Cursor enthält zu viele Einzelbilder. Unterstützt werden bis zu %d.",
        "error.cursorDimensionsTooLarge": "Das Cursorbild ist zu groß. Jede Seite darf höchstens %d Pixel haben.",
        "error.cursorRenderedDimensionsTooLarge": "Das Cursorbild ist in der gewählten Skalierung zu groß. Jede Seite darf höchstens %d Pixel haben.",
        "error.cursorRenderedPayloadTooLarge": "Der gerenderte animierte Cursor ist zu groß. Verringern Sie die Cursorgröße oder die Anzahl der Einzelbilder.",
        "error.mousecapeConflict": "Mousecape oder mousecloak läuft derzeit (%@). Beenden Sie es, bevor Sie Cursie-Cursor anwenden, damit die Apps nicht um den Systemcursor konkurrieren."
    ]

    private static let french: [String: String] = [
        "update.available": "Mise à jour",
        "menu.checkForUpdates": "Rechercher les mises à jour…",
        "app.additionalCursors": "Curseurs supplémentaires",
        "app.additionalCursorHint": "Par défaut : utiliser le curseur par défaut de macOS.\nSauf cas particulier, il vaut mieux les laisser tels quels.",
        "app.noCursorLoaded": "Aucun curseur chargé",
        "app.loadCursorFolderHint": "Chargez un dossier de curseurs, puis choisissez un rôle dans la liste à gauche pour afficher l’aperçu.",
        "app.automaticMatchFailed": "Échec de la correspondance automatique",
        "app.automaticMatchFailedArrowFallback": "Échec de la correspondance automatique · curseur normal utilisé",
        "app.manualOverride": "Remplacement manuel",
        "app.automaticallyMatched": "Correspondance automatique",
        "app.automaticallyMatchedFromFolder": "Fichier associé automatiquement depuis le dossier",
        "app.changeCursorFile": "Changer le fichier du curseur",
        "app.arrowFallbackDescription": "Aucun curseur dédié n’a été trouvé pour ce rôle. Le curseur standard du thème est utilisé à la place.",
        "app.automaticMatchKeywords": "Mots-clés de correspondance automatique",
        "app.inheritedMatchKeywords": "Mots-clés suggérés",
        "app.mousecape": "Type Mousecape",
        "app.currentSource": "Source actuelle",
        "app.automaticallyMatchedInsideSelectedFolder": "Correspondance automatique dans le dossier sélectionné",
        "app.cursorFolder": "Dossier de curseurs",
        "app.noFolderSelected": "Aucun dossier sélectionné",
        "app.chooseFolder": "Choisir un dossier",
        "app.cursorWillAppearHere": "Le curseur apparaîtra ici après chargement.",
        "systemApply.apply": "Appliquer aux curseurs système",
        "systemApply.openPointerSettings": "Réinitialiser le curseur par défaut dans les réglages macOS",
        "systemApply.pointerSettingsHint": "Dans les réglages du pointeur de macOS, choisissez « Réinitialiser les couleurs » pour retrouver le curseur par défaut.",
        "systemApply.progressTitle": "Application des curseurs système...",
        "systemApply.progressPreparing": "Préparation du jeu de curseurs sélectionné.",
        "systemApply.progressRendering": "Lecture des fichiers de curseur et préparation des images.",
        "systemApply.progressRegistering": "Enregistrement des curseurs dans macOS.",
        "systemApply.progressAgent": "Préparation de l’application automatique du curseur à l’ouverture de session.",
        "systemApply.progressDone": "Terminé.",
        "systemApply.successTitle": "Appliqué",
        "preview.large": "Grand aperçu",
        "preview.actualSize": "Taille réelle",
        "export.sizeLabel": "Taille du curseur",
        "alert.errorTitle": "Erreur",
        "alert.ok": "OK",
        "alert.dropCursorSelectionRequired": "Choisissez un rôle de curseur à gauche avant de déposer un fichier de curseur.",
        "alert.dropLoadFailed": "L’élément déposé n’a pas pu être lu. Déposez à nouveau le fichier ou le dossier.",
        "export.unknownAuthor": "Inconnu",
        "role.arrow": "Normal / Pointeur",
        "role.text": "Texte",
        "role.link": "Lien",
        "role.location": "Sélection d’un emplacement",
        "role.precision": "Précision / Réticule",
        "role.move": "Déplacer",
        "role.unavailable": "Indisponible",
        "role.busy": "Occupé",
        "role.working": "Arrière-plan / En cours",
        "role.help": "Aide",
        "role.handwriting": "Écriture manuscrite",
        "role.person": "Personne",
        "role.alternate": "Alternatif",
        "role.verticalResize": "Redimensionnement vertical",
        "role.horizontalResize": "Redimensionnement horizontal",
        "role.diagonalResizeNWSE": "Redimensionnement diagonal 1",
        "role.diagonalResizeNESW": "Redimensionnement diagonal 2",
        "role.contextualMenu": "Menu contextuel",
        "role.dragCopy": "Glisser pour copier",
        "role.dragLink": "Glisser pour lier",
        "role.disappearingItem": "Élément disparaissant",
        "role.closeHand": "Main fermée",
        "role.openHand": "Main ouverte",
        "role.resizeUp": "Redimensionner vers le haut",
        "role.resizeDown": "Redimensionner vers le bas",
        "role.resizeLeft": "Redimensionner vers la gauche",
        "role.resizeRight": "Redimensionner vers la droite",
        "role.verticalIBeam": "Sélection de texte verticale",
        "role.zoomIn": "Zoom avant",
        "role.zoomOut": "Zoom arrière",
        "status.startingUp": "Initialisation...",
        "status.chooseCursorFolder": "Choisissez un dossier de curseurs.",
        "status.supportedFiles": "Les fichiers pris en charge sont .ani et .cur.",
        "status.systemApplySuccess": "Appliqué aux curseurs système. L’assistant de connexion est activé.",
        "status.systemApplyWarning": "Appliqué aux curseurs système, mais l’assistant de connexion n’a pas été confirmé : %@",
        "status.systemApplyFailure": "Échec de l’application des curseurs système : %@",
        "status.loaded": "%@ chargé · %d/%d rôles associés",
        "status.loadFailure": "Échec du chargement : %@",
        "panel.chooseFolder": "Choisir un dossier",
        "panel.chooseCursor": "Choisir un curseur",
        "menu.language": "Langue",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Aucun dossier de thème sélectionné.",
        "error.themeFileMissing": "Fichier de thème introuvable : %@",
        "error.aniParsingFailed": "Échec de l’analyse ANI : %@",
        "error.unsupportedCursorPayload": "Impossible de lire l’image du curseur.",
        "error.invalidThemeSelection.noCursorFiles": "Ce dossier ne contient pas de fichiers de curseur directement utilisables.\nChoisissez un dossier contenant des fichiers .ani ou .cur à la racine.",
        "error.unsupportedExtension": "Extension non prise en charge : %@",
        "error.invalidRiffAconHeader": "Le fichier ne possède pas d’en-tête RIFF ACON valide.",
        "error.invalidChunkLength": "La longueur du bloc est invalide.",
        "error.noFrames": "Le fichier ne contient aucune image d’animation.",
        "error.invalidIconChunkLength": "La longueur du bloc icon est invalide.",
        "error.curTooShort": "Les données CUR sont trop courtes.",
        "error.invalidCurHeader": "Le fichier ne contient pas d’en-tête CUR valide.",
        "error.invalidCurEmbeddedRange": "La plage de l’image CUR intégrée est invalide.",
        "error.noCursorsToExport": "Aucun curseur à exporter.",
        "error.systemApplyExecutableMissing": "Cursie n’a pas trouvé son exécutable pour l’assistant de curseur à l’ouverture de session.",
        "error.systemApplyBundleIdentifierMissing": "Cursie n’a pas pu déterminer l’identifiant d’app requis par l’assistant de connexion.",
        "error.installCursieBeforeApplying": "Placez Cursie dans le dossier Applications, puis réessayez. Une app exécutée depuis une image disque ne peut pas rétablir le curseur après la connexion.",
        "error.cursorFileTooLarge": "Le fichier de curseur est trop volumineux. La taille maximale prise en charge est de %d Mo.",
        "error.cursorTooManyFrames": "Le curseur contient trop d’images. Jusqu’à %d images sont prises en charge.",
        "error.cursorDimensionsTooLarge": "L’image du curseur est trop grande. Chaque côté peut mesurer au maximum %d pixels.",
        "error.cursorRenderedDimensionsTooLarge": "L’image du curseur est trop grande à l’échelle choisie. Chaque côté peut mesurer au maximum %d pixels.",
        "error.cursorRenderedPayloadTooLarge": "Le curseur animé traité est trop volumineux. Réduisez sa taille ou son nombre d’images.",
        "error.mousecapeConflict": "Mousecape ou mousecloak est en cours d’exécution (%@). Quittez-le avant d’appliquer les curseurs Cursie afin que les deux apps ne se disputent pas le curseur système."
    ]

    private static let spanish: [String: String] = [
        "update.available": "Actualizar",
        "menu.checkForUpdates": "Buscar actualizaciones…",
        "app.additionalCursors": "Cursores adicionales",
        "app.additionalCursorHint": "Valor predeterminado: usar el cursor predeterminado de macOS.\nSalvo en casos especiales, es mejor dejarlos tal como están.",
        "app.noCursorLoaded": "No hay cursores cargados",
        "app.loadCursorFolderHint": "Carga una carpeta de cursores y luego elige un rol en la lista de la izquierda para ver la vista previa.",
        "app.automaticMatchFailed": "Falló la coincidencia automática",
        "app.automaticMatchFailedArrowFallback": "Falló la coincidencia automática · usando cursor normal",
        "app.manualOverride": "Asignación manual",
        "app.automaticallyMatched": "Coincidencia automática",
        "app.automaticallyMatchedFromFolder": "Archivo asignado automáticamente desde la carpeta",
        "app.changeCursorFile": "Cambiar archivo de cursor",
        "app.arrowFallbackDescription": "No se encontró un cursor dedicado para este rol, así que se usa el cursor normal del tema.",
        "app.automaticMatchKeywords": "Palabras clave de coincidencia automática",
        "app.inheritedMatchKeywords": "Palabras clave sugeridas",
        "app.mousecape": "Tipo de Mousecape",
        "app.currentSource": "Origen actual",
        "app.automaticallyMatchedInsideSelectedFolder": "Coincidencia automática dentro de la carpeta seleccionada",
        "app.cursorFolder": "Carpeta de cursores",
        "app.noFolderSelected": "No se ha seleccionado ninguna carpeta",
        "app.chooseFolder": "Elegir carpeta",
        "app.cursorWillAppearHere": "El cursor aparecerá aquí después de cargarlo.",
        "systemApply.apply": "Aplicar a cursores del sistema",
        "systemApply.openPointerSettings": "Restablecer el cursor predeterminado en Ajustes de macOS",
        "systemApply.pointerSettingsHint": "En los ajustes del puntero de macOS, elige “Restablecer colores” para volver al cursor predeterminado.",
        "systemApply.progressTitle": "Aplicando cursores del sistema...",
        "systemApply.progressPreparing": "Preparando el conjunto de cursores seleccionado.",
        "systemApply.progressRendering": "Leyendo archivos de cursor y preparando imágenes.",
        "systemApply.progressRegistering": "Registrando cursores en macOS.",
        "systemApply.progressAgent": "Preparando la aplicación automática del cursor al iniciar sesión.",
        "systemApply.progressDone": "Listo.",
        "systemApply.successTitle": "Aplicado",
        "preview.large": "Vista ampliada",
        "preview.actualSize": "Tamaño real",
        "export.sizeLabel": "Tamaño del cursor",
        "alert.errorTitle": "Error",
        "alert.ok": "Aceptar",
        "alert.dropCursorSelectionRequired": "Elige un rol de cursor a la izquierda antes de soltar un archivo de cursor.",
        "alert.dropLoadFailed": "No se pudo leer el elemento soltado. Vuelve a soltar el archivo o la carpeta.",
        "export.unknownAuthor": "Desconocido",
        "role.arrow": "Normal / Puntero",
        "role.text": "Texto",
        "role.link": "Enlace",
        "role.location": "Selección de ubicación",
        "role.precision": "Precisión / Cruz",
        "role.move": "Mover",
        "role.unavailable": "No disponible",
        "role.busy": "Ocupado",
        "role.working": "Segundo plano / En curso",
        "role.help": "Ayuda",
        "role.handwriting": "Escritura a mano",
        "role.person": "Persona",
        "role.alternate": "Alternativo",
        "role.verticalResize": "Redimensionado vertical",
        "role.horizontalResize": "Redimensionado horizontal",
        "role.diagonalResizeNWSE": "Redimensionado diagonal 1",
        "role.diagonalResizeNESW": "Redimensionado diagonal 2",
        "role.contextualMenu": "Menú contextual",
        "role.dragCopy": "Arrastrar para copiar",
        "role.dragLink": "Arrastrar para enlazar",
        "role.disappearingItem": "Elemento que desaparece",
        "role.closeHand": "Mano cerrada",
        "role.openHand": "Mano abierta",
        "role.resizeUp": "Redimensionar hacia arriba",
        "role.resizeDown": "Redimensionar hacia abajo",
        "role.resizeLeft": "Redimensionar hacia la izquierda",
        "role.resizeRight": "Redimensionar hacia la derecha",
        "role.verticalIBeam": "Selección de texto vertical",
        "role.zoomIn": "Acercar",
        "role.zoomOut": "Alejar",
        "status.startingUp": "Iniciando...",
        "status.chooseCursorFolder": "Elige una carpeta de cursores.",
        "status.supportedFiles": "Los archivos compatibles son .ani y .cur.",
        "status.systemApplySuccess": "Aplicado a los cursores del sistema. El asistente de inicio de sesión está activado.",
        "status.systemApplyWarning": "Aplicado a los cursores del sistema, pero no se pudo confirmar el asistente de inicio de sesión: %@",
        "status.systemApplyFailure": "Error al aplicar los cursores del sistema: %@",
        "status.loaded": "%@ cargado · %d/%d roles asignados",
        "status.loadFailure": "Error al cargar: %@",
        "panel.chooseFolder": "Elegir carpeta",
        "panel.chooseCursor": "Elegir cursor",
        "menu.language": "Idioma",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "No se ha seleccionado ninguna carpeta de tema.",
        "error.themeFileMissing": "Falta el archivo del tema: %@",
        "error.aniParsingFailed": "Error al analizar ANI: %@",
        "error.unsupportedCursorPayload": "No se pudo leer el fotograma del cursor como imagen.",
        "error.invalidThemeSelection.noCursorFiles": "Esta carpeta no contiene archivos de cursor que puedan usarse directamente.\nElige una carpeta que contenga archivos .ani o .cur en el nivel superior.",
        "error.unsupportedExtension": "Extensión no compatible: %@",
        "error.invalidRiffAconHeader": "El archivo no tiene un encabezado RIFF ACON válido.",
        "error.invalidChunkLength": "La longitud del bloque es inválida.",
        "error.noFrames": "El archivo no contiene fotogramas.",
        "error.invalidIconChunkLength": "La longitud del bloque icon es inválida.",
        "error.curTooShort": "Los datos CUR son demasiado cortos.",
        "error.invalidCurHeader": "El archivo no contiene un encabezado CUR válido.",
        "error.invalidCurEmbeddedRange": "El rango de la imagen CUR incrustada es inválido.",
        "error.noCursorsToExport": "No hay cursores para exportar.",
        "error.systemApplyExecutableMissing": "Cursie no pudo localizar su ejecutable para el asistente de cursor al iniciar sesión.",
        "error.systemApplyBundleIdentifierMissing": "Cursie no pudo determinar el identificador de la app necesario para el asistente de inicio de sesión.",
        "error.installCursieBeforeApplying": "Mueve Cursie a la carpeta Aplicaciones e inténtalo de nuevo. Una app ejecutada desde una imagen de disco no puede restaurar el cursor después de iniciar sesión.",
        "error.cursorFileTooLarge": "El archivo de cursor es demasiado grande. Se admiten hasta %d MB.",
        "error.cursorTooManyFrames": "El cursor tiene demasiados fotogramas. Se admiten hasta %d.",
        "error.cursorDimensionsTooLarge": "La imagen del cursor es demasiado grande. Cada lado puede tener hasta %d píxeles.",
        "error.cursorRenderedDimensionsTooLarge": "La imagen del cursor es demasiado grande con la escala elegida. Cada lado puede tener hasta %d píxeles.",
        "error.cursorRenderedPayloadTooLarge": "El cursor animado procesado es demasiado grande. Reduce el tamaño del cursor o el número de fotogramas.",
        "error.mousecapeConflict": "Mousecape o mousecloak se está ejecutando (%@). Ciérralo antes de aplicar los cursores de Cursie para que ambas apps no compitan por el cursor del sistema."
    ]

    private static let portugueseBrazil: [String: String] = [
        "update.available": "Atualizar",
        "menu.checkForUpdates": "Verificar atualizações…",
        "app.additionalCursors": "Cursores adicionais",
        "app.additionalCursorHint": "Padrão: usar o cursor padrão do macOS.\nA menos que haja um motivo especial, é melhor deixar como está.",
        "app.noCursorLoaded": "Nenhum cursor carregado",
        "app.loadCursorFolderHint": "Carregue uma pasta de cursores e depois escolha uma função na lista à esquerda para visualizar.",
        "app.automaticMatchFailed": "Falha na correspondência automática",
        "app.automaticMatchFailedArrowFallback": "Falha na correspondência automática · usando o cursor padrão",
        "app.manualOverride": "Substituição manual",
        "app.automaticallyMatched": "Correspondência automática",
        "app.automaticallyMatchedFromFolder": "Arquivo associado automaticamente da pasta",
        "app.changeCursorFile": "Alterar arquivo do cursor",
        "app.arrowFallbackDescription": "Não foi encontrado um cursor dedicado para esta função, então o cursor padrão do tema está sendo usado no lugar.",
        "app.automaticMatchKeywords": "Palavras-chave de correspondência automática",
        "app.inheritedMatchKeywords": "Palavras-chave sugeridas",
        "app.mousecape": "Tipo do Mousecape",
        "app.currentSource": "Fonte atual",
        "app.automaticallyMatchedInsideSelectedFolder": "Correspondência automática dentro da pasta selecionada",
        "app.cursorFolder": "Pasta de cursores",
        "app.noFolderSelected": "Nenhuma pasta selecionada",
        "app.chooseFolder": "Escolher pasta",
        "app.cursorWillAppearHere": "O cursor aparecerá aqui depois que você carregar um.",
        "systemApply.apply": "Aplicar aos cursores do sistema",
        "systemApply.openPointerSettings": "Redefinir o cursor padrão nos Ajustes do macOS",
        "systemApply.pointerSettingsHint": "Nos ajustes do ponteiro do macOS, escolha “Redefinir Cores” para voltar ao cursor padrão.",
        "systemApply.progressTitle": "Aplicando cursores do sistema...",
        "systemApply.progressPreparing": "Preparando o conjunto de cursores selecionado.",
        "systemApply.progressRendering": "Lendo arquivos de cursor e preparando imagens.",
        "systemApply.progressRegistering": "Registrando cursores no macOS.",
        "systemApply.progressAgent": "Preparando a aplicação automática do cursor ao iniciar sessão.",
        "systemApply.progressDone": "Concluído.",
        "systemApply.successTitle": "Aplicado",
        "preview.large": "Visualização ampliada",
        "preview.actualSize": "Tamanho real",
        "export.sizeLabel": "Tamanho do cursor",
        "alert.errorTitle": "Erro",
        "alert.ok": "OK",
        "alert.dropCursorSelectionRequired": "Escolha uma função de cursor à esquerda antes de soltar um arquivo de cursor.",
        "alert.dropLoadFailed": "Não foi possível ler o item solto. Solte o arquivo ou a pasta novamente.",
        "export.unknownAuthor": "Desconhecido",
        "role.arrow": "Normal / Ponteiro",
        "role.text": "Texto",
        "role.link": "Link",
        "role.location": "Seleção de local",
        "role.precision": "Precisão / Cruz",
        "role.move": "Mover",
        "role.unavailable": "Indisponível",
        "role.busy": "Ocupado",
        "role.working": "Segundo plano / Em andamento",
        "role.help": "Ajuda",
        "role.handwriting": "Escrita à mão",
        "role.person": "Pessoa",
        "role.alternate": "Alternativo",
        "role.verticalResize": "Redimensionamento vertical",
        "role.horizontalResize": "Redimensionamento horizontal",
        "role.diagonalResizeNWSE": "Redimensionamento diagonal 1",
        "role.diagonalResizeNESW": "Redimensionamento diagonal 2",
        "role.contextualMenu": "Menu contextual",
        "role.dragCopy": "Arrastar para copiar",
        "role.dragLink": "Arrastar para criar link",
        "role.disappearingItem": "Item desaparecendo",
        "role.closeHand": "Mão fechada",
        "role.openHand": "Mão aberta",
        "role.resizeUp": "Redimensionar para cima",
        "role.resizeDown": "Redimensionar para baixo",
        "role.resizeLeft": "Redimensionar para a esquerda",
        "role.resizeRight": "Redimensionar para a direita",
        "role.verticalIBeam": "Seleção vertical de texto",
        "role.zoomIn": "Ampliar",
        "role.zoomOut": "Reduzir",
        "status.startingUp": "Iniciando...",
        "status.chooseCursorFolder": "Escolha uma pasta de cursores.",
        "status.supportedFiles": "Os arquivos compatíveis são .ani e .cur.",
        "status.systemApplySuccess": "Aplicado aos cursores do sistema. O auxiliar de login está ativado.",
        "status.systemApplyWarning": "Aplicado aos cursores do sistema, mas o auxiliar de login não foi confirmado: %@",
        "status.systemApplyFailure": "Falha ao aplicar os cursores do sistema: %@",
        "status.loaded": "%@ carregado · %d/%d funções mapeadas",
        "status.loadFailure": "Falha ao carregar: %@",
        "panel.chooseFolder": "Escolher pasta",
        "panel.chooseCursor": "Escolher cursor",
        "menu.language": "Idioma",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Nenhuma pasta de tema foi selecionada.",
        "error.themeFileMissing": "Arquivo de tema ausente: %@",
        "error.aniParsingFailed": "Falha ao analisar ANI: %@",
        "error.unsupportedCursorPayload": "Não foi possível ler o quadro do cursor como imagem.",
        "error.invalidThemeSelection.noCursorFiles": "Esta pasta não contém arquivos de cursor que possam ser usados diretamente.\nEscolha uma pasta que contenha arquivos .ani ou .cur no nível superior.",
        "error.unsupportedExtension": "Extensão não compatível: %@",
        "error.invalidRiffAconHeader": "O arquivo não possui um cabeçalho RIFF ACON válido.",
        "error.invalidChunkLength": "O comprimento do bloco é inválido.",
        "error.noFrames": "O arquivo não contém quadros.",
        "error.invalidIconChunkLength": "O comprimento do bloco icon é inválido.",
        "error.curTooShort": "Os dados CUR são curtos demais.",
        "error.invalidCurHeader": "O arquivo não contém um cabeçalho CUR válido.",
        "error.invalidCurEmbeddedRange": "O intervalo da imagem CUR incorporada é inválido.",
        "error.noCursorsToExport": "Não há cursores para exportar.",
        "error.systemApplyExecutableMissing": "O Cursie não encontrou seu executável para o auxiliar de cursor ao iniciar sessão.",
        "error.systemApplyBundleIdentifierMissing": "O Cursie não conseguiu determinar o identificador do app necessário para o auxiliar de login.",
        "error.installCursieBeforeApplying": "Mova o Cursie para a pasta Aplicativos e tente novamente. Um app executado a partir de uma imagem de disco não pode restaurar o cursor após o login.",
        "error.cursorFileTooLarge": "O arquivo de cursor é grande demais. São aceitos até %d MB.",
        "error.cursorTooManyFrames": "O cursor tem quadros demais. São aceitos até %d.",
        "error.cursorDimensionsTooLarge": "A imagem do cursor é grande demais. Cada lado pode ter no máximo %d pixels.",
        "error.cursorRenderedDimensionsTooLarge": "A imagem do cursor é grande demais na escala escolhida. Cada lado pode ter no máximo %d pixels.",
        "error.cursorRenderedPayloadTooLarge": "O cursor animado processado é grande demais. Reduza o tamanho do cursor ou a quantidade de quadros.",
        "error.mousecapeConflict": "Mousecape ou mousecloak está em execução (%@). Encerre-o antes de aplicar os cursores do Cursie para que os dois apps não disputem o cursor do sistema."
    ]

    private static let italian: [String: String] = [
        "update.available": "Aggiorna",
        "menu.checkForUpdates": "Controlla aggiornamenti…",
        "app.additionalCursors": "Cursori aggiuntivi",
        "app.additionalCursorHint": "Predefinito: usa il cursore predefinito di macOS.\nA meno che non ci sia un caso particolare, è meglio lasciarli così come sono.",
        "app.noCursorLoaded": "Nessun cursore caricato",
        "app.loadCursorFolderHint": "Carica una cartella di cursori, poi scegli un ruolo nell’elenco a sinistra per l’anteprima.",
        "app.automaticMatchFailed": "Associazione automatica non riuscita",
        "app.automaticMatchFailedArrowFallback": "Associazione automatica non riuscita · uso del cursore standard",
        "app.manualOverride": "Sostituzione manuale",
        "app.automaticallyMatched": "Associazione automatica",
        "app.automaticallyMatchedFromFolder": "File associato automaticamente dalla cartella",
        "app.changeCursorFile": "Cambia file cursore",
        "app.arrowFallbackDescription": "Non è stato trovato un cursore dedicato per questo ruolo, quindi viene usato il cursore standard del tema.",
        "app.automaticMatchKeywords": "Parole chiave per l'abbinamento automatico",
        "app.inheritedMatchKeywords": "Parole chiave suggerite",
        "app.mousecape": "Tipo Mousecape",
        "app.currentSource": "Sorgente attuale",
        "app.automaticallyMatchedInsideSelectedFolder": "Associazione automatica nella cartella selezionata",
        "app.cursorFolder": "Cartella cursori",
        "app.noFolderSelected": "Nessuna cartella selezionata",
        "app.chooseFolder": "Scegli cartella",
        "app.cursorWillAppearHere": "Il cursore apparirà qui dopo il caricamento.",
        "systemApply.apply": "Applica ai cursori di sistema",
        "systemApply.openPointerSettings": "Reimposta il cursore predefinito nelle Impostazioni di macOS",
        "systemApply.pointerSettingsHint": "Nelle impostazioni del puntatore di macOS, scegli “Reimposta colori” per tornare al cursore predefinito.",
        "systemApply.progressTitle": "Applicazione dei cursori di sistema...",
        "systemApply.progressPreparing": "Preparazione del set di cursori selezionato.",
        "systemApply.progressRendering": "Lettura dei file cursore e preparazione delle immagini.",
        "systemApply.progressRegistering": "Registrazione dei cursori in macOS.",
        "systemApply.progressAgent": "Preparazione dell’applicazione automatica del cursore all’accesso.",
        "systemApply.progressDone": "Completato.",
        "systemApply.successTitle": "Applicato",
        "preview.large": "Anteprima ingrandita",
        "preview.actualSize": "Dimensione reale",
        "export.sizeLabel": "Dimensione del cursore",
        "alert.errorTitle": "Errore",
        "alert.ok": "OK",
        "alert.dropCursorSelectionRequired": "Scegli un ruolo cursore a sinistra prima di trascinare un file cursore.",
        "alert.dropLoadFailed": "Impossibile leggere l’elemento trascinato. Trascina di nuovo il file o la cartella.",
        "export.unknownAuthor": "Sconosciuto",
        "role.arrow": "Normale / Puntatore",
        "role.text": "Testo",
        "role.link": "Link",
        "role.location": "Selezione posizione",
        "role.precision": "Precisione / Mirino",
        "role.move": "Sposta",
        "role.unavailable": "Non disponibile",
        "role.busy": "Occupato",
        "role.working": "Sfondo / In corso",
        "role.help": "Aiuto",
        "role.handwriting": "Scrittura a mano",
        "role.person": "Persona",
        "role.alternate": "Alternativo",
        "role.verticalResize": "Ridimensionamento verticale",
        "role.horizontalResize": "Ridimensionamento orizzontale",
        "role.diagonalResizeNWSE": "Ridimensionamento diagonale 1",
        "role.diagonalResizeNESW": "Ridimensionamento diagonale 2",
        "role.contextualMenu": "Menu contestuale",
        "role.dragCopy": "Trascina per copiare",
        "role.dragLink": "Trascina per collegare",
        "role.disappearingItem": "Elemento che scompare",
        "role.closeHand": "Mano chiusa",
        "role.openHand": "Mano aperta",
        "role.resizeUp": "Ridimensiona verso l’alto",
        "role.resizeDown": "Ridimensiona verso il basso",
        "role.resizeLeft": "Ridimensiona verso sinistra",
        "role.resizeRight": "Ridimensiona verso destra",
        "role.verticalIBeam": "Selezione testo verticale",
        "role.zoomIn": "Ingrandisci",
        "role.zoomOut": "Riduci",
        "status.startingUp": "Avvio in corso...",
        "status.chooseCursorFolder": "Scegli una cartella di cursori.",
        "status.supportedFiles": "I file supportati sono .ani e .cur.",
        "status.systemApplySuccess": "Applicato ai cursori di sistema. L’helper di accesso è attivo.",
        "status.systemApplyWarning": "Applicato ai cursori di sistema, ma l’helper di accesso non è stato confermato: %@",
        "status.systemApplyFailure": "Applicazione dei cursori di sistema non riuscita: %@",
        "status.loaded": "%@ caricato · %d/%d ruoli associati",
        "status.loadFailure": "Caricamento non riuscito: %@",
        "panel.chooseFolder": "Scegli cartella",
        "panel.chooseCursor": "Scegli cursore",
        "menu.language": "Lingua",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Nessuna cartella del tema selezionata.",
        "error.themeFileMissing": "File del tema mancante: %@",
        "error.aniParsingFailed": "Analisi ANI non riuscita: %@",
        "error.unsupportedCursorPayload": "Impossibile leggere il fotogramma del cursore come immagine.",
        "error.invalidThemeSelection.noCursorFiles": "Questa cartella non contiene file cursore utilizzabili direttamente.\nScegli una cartella che contenga file .ani o .cur al livello superiore.",
        "error.unsupportedExtension": "Estensione non supportata: %@",
        "error.invalidRiffAconHeader": "Il file non ha un’intestazione RIFF ACON valida.",
        "error.invalidChunkLength": "La lunghezza del blocco non è valida.",
        "error.noFrames": "Il file non contiene fotogrammi.",
        "error.invalidIconChunkLength": "La lunghezza del blocco icon non è valida.",
        "error.curTooShort": "I dati CUR sono troppo corti.",
        "error.invalidCurHeader": "Il file non contiene un’intestazione CUR valida.",
        "error.invalidCurEmbeddedRange": "L’intervallo dell’immagine CUR incorporata non è valido.",
        "error.noCursorsToExport": "Non ci sono cursori da esportare.",
        "error.systemApplyExecutableMissing": "Cursie non ha trovato il proprio eseguibile per l’helper cursore all’accesso.",
        "error.systemApplyBundleIdentifierMissing": "Cursie non ha potuto determinare l’identificatore dell’app richiesto dall’helper di accesso.",
        "error.installCursieBeforeApplying": "Sposta Cursie nella cartella Applicazioni e riprova. Un’app eseguita da un’immagine disco non può ripristinare il cursore dopo l’accesso.",
        "error.cursorFileTooLarge": "Il file del cursore è troppo grande. Sono supportati fino a %d MB.",
        "error.cursorTooManyFrames": "Il cursore contiene troppi fotogrammi. Ne sono supportati fino a %d.",
        "error.cursorDimensionsTooLarge": "L’immagine del cursore è troppo grande. Ogni lato può essere lungo al massimo %d pixel.",
        "error.cursorRenderedDimensionsTooLarge": "L’immagine del cursore è troppo grande con la scala scelta. Ogni lato può essere lungo al massimo %d pixel.",
        "error.cursorRenderedPayloadTooLarge": "Il cursore animato elaborato è troppo grande. Riduci le dimensioni o il numero di fotogrammi.",
        "error.mousecapeConflict": "Mousecape o mousecloak è attualmente in esecuzione (%@). Chiudilo prima di applicare i cursori Cursie, così le due app non si contendono il cursore di sistema."
    ]

    private static let russian: [String: String] = [
        "update.available": "Обновить",
        "menu.checkForUpdates": "Проверить наличие обновлений…",
        "app.additionalCursors": "Дополнительные курсоры",
        "app.additionalCursorHint": "По умолчанию: использовать стандартный курсор macOS.\nЕсли нет особой причины, лучше оставить всё как есть.",
        "app.noCursorLoaded": "Нет загруженных курсоров",
        "app.loadCursorFolderHint": "Загрузите папку с курсорами, затем выберите роль в списке слева для предпросмотра.",
        "app.automaticMatchFailed": "Автосопоставление не удалось",
        "app.automaticMatchFailedArrowFallback": "Автосопоставление не удалось · используется обычный курсор",
        "app.manualOverride": "Ручное назначение",
        "app.automaticallyMatched": "Автосопоставление",
        "app.automaticallyMatchedFromFolder": "Файл автоматически сопоставлен из папки",
        "app.changeCursorFile": "Изменить файл курсора",
        "app.arrowFallbackDescription": "Для этой роли не найден отдельный курсор, поэтому используется обычный курсор темы.",
        "app.automaticMatchKeywords": "Ключевые слова автосопоставления",
        "app.inheritedMatchKeywords": "Рекомендуемые ключевые слова",
        "app.mousecape": "Тип Mousecape",
        "app.currentSource": "Текущий источник",
        "app.automaticallyMatchedInsideSelectedFolder": "Автосопоставление внутри выбранной папки",
        "app.cursorFolder": "Папка курсоров",
        "app.noFolderSelected": "Папка не выбрана",
        "app.chooseFolder": "Выбрать папку",
        "app.cursorWillAppearHere": "Курсор появится здесь после загрузки.",
        "systemApply.apply": "Применить к системным курсорам",
        "systemApply.openPointerSettings": "Сбросить курсор по умолчанию в настройках macOS",
        "systemApply.pointerSettingsHint": "В настройках указателя macOS выберите «Сбросить цвета», чтобы вернуть стандартный курсор.",
        "systemApply.progressTitle": "Применение системных курсоров...",
        "systemApply.progressPreparing": "Подготовка выбранного набора курсоров.",
        "systemApply.progressRendering": "Чтение файлов курсоров и подготовка изображений.",
        "systemApply.progressRegistering": "Регистрация курсоров в macOS.",
        "systemApply.progressAgent": "Подготовка автоматического применения курсора при входе.",
        "systemApply.progressDone": "Готово.",
        "systemApply.successTitle": "Применено",
        "preview.large": "Увеличенный просмотр",
        "preview.actualSize": "Фактический размер",
        "export.sizeLabel": "Размер курсора",
        "alert.errorTitle": "Ошибка",
        "alert.ok": "ОК",
        "alert.dropCursorSelectionRequired": "Выберите роль курсора слева, прежде чем перетаскивать файл курсора.",
        "alert.dropLoadFailed": "Не удалось прочитать перетащенный элемент. Перетащите файл или папку еще раз.",
        "export.unknownAuthor": "Неизвестно",
        "role.arrow": "Обычный / Указатель",
        "role.text": "Текст",
        "role.link": "Ссылка",
        "role.location": "Выбор местоположения",
        "role.precision": "Точность / Перекрестие",
        "role.move": "Перемещение",
        "role.unavailable": "Недоступно",
        "role.busy": "Занят",
        "role.working": "Фон / В работе",
        "role.help": "Справка",
        "role.handwriting": "Рукописный",
        "role.person": "Человек",
        "role.alternate": "Альтернативный",
        "role.verticalResize": "Вертикальное изменение размера",
        "role.horizontalResize": "Горизонтальное изменение размера",
        "role.diagonalResizeNWSE": "Диагональное изменение размера 1",
        "role.diagonalResizeNESW": "Диагональное изменение размера 2",
        "role.contextualMenu": "Контекстное меню",
        "role.dragCopy": "Перетаскивание для копирования",
        "role.dragLink": "Перетаскивание для создания ссылки",
        "role.disappearingItem": "Исчезающий элемент",
        "role.closeHand": "Закрытая ладонь",
        "role.openHand": "Открытая ладонь",
        "role.resizeUp": "Изменение размера вверх",
        "role.resizeDown": "Изменение размера вниз",
        "role.resizeLeft": "Изменение размера влево",
        "role.resizeRight": "Изменение размера вправо",
        "role.verticalIBeam": "Вертикальное выделение текста",
        "role.zoomIn": "Увеличить",
        "role.zoomOut": "Уменьшить",
        "status.startingUp": "Запуск...",
        "status.chooseCursorFolder": "Выберите папку с курсорами.",
        "status.supportedFiles": "Поддерживаются файлы .ani и .cur.",
        "status.systemApplySuccess": "Применено к системным курсорам. Помощник входа включен.",
        "status.systemApplyWarning": "Применено к системным курсорам, но помощник входа не подтвержден: %@",
        "status.systemApplyFailure": "Не удалось применить системные курсоры: %@",
        "status.loaded": "Загружено %@ · сопоставлено %d/%d ролей",
        "status.loadFailure": "Ошибка загрузки: %@",
        "panel.chooseFolder": "Выбрать папку",
        "panel.chooseCursor": "Выбрать курсор",
        "menu.language": "Язык",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Папка темы не выбрана.",
        "error.themeFileMissing": "Файл темы отсутствует: %@",
        "error.aniParsingFailed": "Ошибка разбора ANI: %@",
        "error.unsupportedCursorPayload": "Не удалось прочитать кадр курсора как изображение.",
        "error.invalidThemeSelection.noCursorFiles": "В этой папке нет файлов курсоров, которые можно использовать напрямую.\nВыберите папку, в верхнем уровне которой есть файлы .ani или .cur.",
        "error.unsupportedExtension": "Неподдерживаемое расширение: %@",
        "error.invalidRiffAconHeader": "Файл не содержит корректный заголовок RIFF ACON.",
        "error.invalidChunkLength": "Недопустимая длина блока.",
        "error.noFrames": "Файл не содержит кадров.",
        "error.invalidIconChunkLength": "Недопустимая длина блока icon.",
        "error.curTooShort": "Данные CUR слишком короткие.",
        "error.invalidCurHeader": "Файл не содержит корректный заголовок CUR.",
        "error.invalidCurEmbeddedRange": "Недопустимый диапазон встроенного изображения CUR.",
        "error.noCursorsToExport": "Нет курсоров для экспорта.",
        "error.systemApplyExecutableMissing": "Cursie не удалось найти исполняемый файл для помощника курсора при входе.",
        "error.systemApplyBundleIdentifierMissing": "Cursie не удалось определить идентификатор приложения, необходимый помощнику входа.",
        "error.installCursieBeforeApplying": "Переместите Cursie в папку «Программы» и повторите попытку. Приложение, запущенное с образа диска, не сможет восстановить курсор после входа.",
        "error.cursorFileTooLarge": "Файл курсора слишком большой. Поддерживается размер до %d МБ.",
        "error.cursorTooManyFrames": "В курсоре слишком много кадров. Поддерживается до %d кадров.",
        "error.cursorDimensionsTooLarge": "Изображение курсора слишком большое. Каждая сторона может быть не более %d пикселей.",
        "error.cursorRenderedDimensionsTooLarge": "При выбранном масштабе изображение курсора слишком большое. Каждая сторона может быть не более %d пикселей.",
        "error.cursorRenderedPayloadTooLarge": "Обработанный анимированный курсор слишком большой. Уменьшите размер курсора или количество кадров.",
        "error.mousecapeConflict": "Mousecape или mousecloak сейчас запущен (%@). Закройте его перед применением курсоров Cursie, чтобы приложения не конфликтовали за системный курсор."
    ]
}
